cabal-version: 3.0
name:          nike
version:       0.1.0
synopsis:      Fixture package for hypha sub-library tests
build-type:    Simple

library
  default-language: Haskell2010
  hs-source-dirs:   src
  exposed-modules:  Nike.Main
  build-depends:    base

library internal
  default-language: Haskell2010
  hs-source-dirs:   internal-src
  exposed-modules:  Nike.Internal.Helpers
  build-depends:    base

library bench
  default-language: Haskell2010
  hs-source-dirs:   bench-src
  exposed-modules:  Nike.Bench.Suite
  build-depends:    base

executable nike-cli
  default-language: Haskell2010
  hs-source-dirs:   app
  main-is:          Main.hs
  build-depends:    base

executable wrap
  default-language: Haskell2010
  hs-source-dirs:   app/wrap
  main-is:          Main.hs
  build-depends:    base
